### ISSUE TITLE
The height of the menu item is changing slightly during navigation with keyboard

### ISSUE THREAD

**Issue by sophieH29** [microsoft/fluent-ui-react#1338] opened 2019-05-14 15:53 UTC
![sizechange_focusissue](https://user-images.githubusercontent.com/8460706/57712580-1c518f80-7671-11e9-8f19-bed9957060c9.gif)

**Comment by miroslavstastny** [comment] 2019-09-05 22:12
Duplicate of #1504

**Closed as completed by miroslavstastny** 2019-09-05 22:12 UTC
Labels: vsts
