### ISSUE TITLE
Allow to disable Dropdown component

### ISSUE THREAD

**Issue by sushruth** [microsoft/fluent-ui-react#2277] opened 2020-01-28 00:30 UTC
## Feature Request

A feature to disable dropdowns would be pretty great. I assume the use case is fairly common.

### Problem description
Need to disable dropdown based on certain criteria. We currently cannot.

### Proposed solution
Allow disabling dropdown

### MVP
NA

**Comment by jurokapsiar** [comment] 2020-02-21 14:34
Duplicate of #1615

**Closed as completed by jurokapsiar** 2020-02-21 14:34 UTC
Labels: vsts
