### ISSUE TITLE
How to use components without provider?

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluent-ui-react#2251] opened 2020-01-16 10:32 UTC
How to use the components without `<Provider>`  (like  `office-ui-fabric-react` does) ?

When test some components with fluent-ui-react, it will show errors with a Provider.
It's unfriendly and ugly to wrap all components with a Provider in all tests.

**Comment by jurokapsiar** [comment] 2020-02-21 14:31
Closing, duplicate of #1594

**Closed as completed** 2020-02-22 12:54 UTC
Labels: vsts
