### ISSUE TITLE
Avatar high contrast mode is not correct

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#738] opened 2019-01-16 19:32 UTC
### Steps
When switching theme to high contrast mode, the user is supposed to see a thin white border on the avatar and the status should have white background and black color.

### Expected Result
![image](https://user-images.githubusercontent.com/1826985/51273689-a5133400-19cd-11e9-85e3-52e9ab64ef19.png)

### Actual Result
![image](https://user-images.githubusercontent.com/1826985/51273777-ce33c480-19cd-11e9-8872-71fbb01ec71c.png)

### Version
0.13.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by codepretty** [comment] 2019-01-22 22:41
Status in the Teams app uses a base64 encoded background image, not an inline SVG. The image is swapped out in css each time a user changes to a different theme. Because the it is so teams specific, I don't think the css swapping of images belongs in Stardust. However, we probably should have an example of a status that uses a background image for testing and to avoid any regressions.

For this issue, we should add the white border around the picture for contrast theme and add an example to the docs that shows a status as a background image in Stardust. The swapping of status background images should be handled elsewhere.

**Comment by kuzhelov** [comment] 2019-02-01 11:37
fixed in #795

**Closed as completed** 2019-02-01 11:37 UTC
Labels: vsts
